  package org.algos.metrics;
    
    import org.junit.jupiter.api.Test;
    import static org.junit.jupiter.api.Assertions.*;
    
    class MetricsTest {

    @Test
    void depthTrackingWorks() {
    Metrics m = new Metrics();
    m.enterRecursion(); // depth = 1
    m.enterRecursion(); // depth = 2
    m.exitRecursion();  // back to 1
    m.exitRecursion();  // back to 0
    assertEquals(2, m.getMaxDepth());
    }

    @Test
    void countersWork() {
    Metrics m = new Metrics();
    m.incComparisons();
    m.addAllocations(5);
    assertEquals(1, m.getComparisons());
    assertEquals(5, m.getAllocations());
    }
  }
